# -*- coding: utf-8 -*-
"""LR3 ReLU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFiffxs6WEK8ceZ8FHvtCFYQg1bF8RVX
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.title("ReLU Activation Function")

st.write("Rectified Linear Unit (ReLU):  f(x) = max(0, x)")

# Input range slider
x_min, x_max = st.slider("Select input range", -10, 10, (-5, 5))

x = np.linspace(x_min, x_max, 400)
y = np.maximum(0, x)

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel("Input (x)")
ax.set_ylabel("Output (ReLU)")
ax.set_title("ReLU Activation Function")
ax.grid(True)

st.pyplot(fig)