# -*- coding: utf-8 -*-
"""LR3 ReLU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFiffxs6WEK8ceZ8FHvtCFYQg1bF8RVX
"""

import streamlit as st
import numpy as np
import pandas as pd

st.set_page_config(page_title="ReLU Activation Function")

st.title("ReLU Activation Function")
st.write("**Formula:**  f(x) = max(0, x)")

# Slider for input range
x_min, x_max = st.slider(
    "Select input range",
    min_value=-10.0,
    max_value=10.0,
    value=(-5.0, 5.0)
)

# Generate data
x = np.linspace(x_min, x_max, 400)
y = np.maximum(0, x)

# Create DataFrame
data = pd.DataFrame({
    "x": x,
    "ReLU(x)": y
})

# Plot using Streamlit native chart
st.line_chart(data.set_index("x"))

st.success("ReLU activation function visualised successfully.")