# -*- coding: utf-8 -*-
"""LR3_Tanh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln9hhRoy3mnYAvUX-WUQy-yQoT-s0_UQ
"""

import streamlit as st
import numpy as np
import pandas as pd

st.set_page_config(page_title="Tanh Activation Function")

st.title("Tanh Activation Function")
st.write("**Formula:**  f(x) = tanh(x)")

# Slider for input range
x_min, x_max = st.slider(
    "Select input range",
    min_value=-10.0,
    max_value=10.0,
    value=(-5.0, 5.0)
)

# Generate data
x = np.linspace(x_min, x_max, 400)
y = np.tanh(x)

# Create DataFrame
data = pd.DataFrame({
    "x": x,
    "Tanh(x)": y
})

# Plot
st.line_chart(data.set_index("x"))

st.success("Tanh activation function visualised successfully.")