# -*- coding: utf-8 -*-
"""LR3_Sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSmdi3a0LnkxUKVyaWTGTVG4sUrYSYSG
"""

import streamlit as st
import numpy as np
import pandas as pd

st.set_page_config(page_title="Sigmoid Activation Function")

st.title("Sigmoid Activation Function")
st.write("**Formula:**  f(x) = 1 / (1 + e⁻ˣ)")

# Slider for input range
x_min, x_max = st.slider(
    "Select input range",
    min_value=-10.0,
    max_value=10.0,
    value=(-5.0, 5.0)
)

# Generate data
x = np.linspace(x_min, x_max, 400)
y = 1 / (1 + np.exp(-x))

# Create DataFrame
data = pd.DataFrame({
    "x": x,
    "Sigmoid(x)": y
})

# Plot
st.line_chart(data.set_index("x"))

st.success("Sigmoid activation function visualised successfully.")